(add-to-list 'load-path (expand-file-name "modules" prelude-personal-dir))

(require 'personal-private)
(require 'personal-eshell)
(require 'personal-font)
(require 'personal-osx)
(require 'personal-ui)
(require 'personal-misc)
(require 'personal-xml)
(require 'personal-rust)
(require 'personal-org)
(require 'personal-ts)
